//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WTracker.rc
//
#define IDC_PHYSICAL_MEM                101
#define ID_CHACO_STATUS_BAR             103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_SPLASH                      105
#define IDF_CHACO_REGULAR               105
#define IDF_CHACO_BOLD                  106
#define IDC_DISK_SPACE                  107
#define IDR_AVI_BOOKS                   107
#define IDR_MAINFRAME                   128
#define IDD_PREF_CONNECTION             132
#define IDB_CHACO_LOGO                  142
#define IDD_PREF_FONT                   147
#define IDD_DIALOG1                     148
#define IDB_BITMAP1                     149
#define IDD_CACHE                       150
#define IDD_NETWORK                     151
#define IDD_BETA_AGREEMENT              152
#define IDR_COPYRIGHT                   153
#define IDR_DISCLAIMER                  154
#define IDB_LOGO_BITMAP                 155
#define IDD_LOCBAR                      157
#define IDB_BITMAP2                     158
#define IDD_OPEN_LOCATION               159
#define IDR_CHACO_DIB                   161
#define IDD_ABOUT_BOX                   512
#define IDD_LOGIN                       513
#define IDD_PREF_DEBUG                  514
#define IDD_ABOUT_DISCLAIMER            515
#define IDD_ABOUT_TEAM                  516
#define IDD_ACCOUNT_PERSONAL            517
#define IDD_ACCOUNT_NAME                518
#define IDD_ACCOUNT_ADDRESS             519
#define IDD_PREF_COLORS                 522
#define IDC_BIG_ICON                    1000
#define IDC_EDIT_ADDRESS                1004
#define IDC_CONN_EDIT_ADDRESS           1004
#define IDC_RAD_INTERNET                1005
#define IDC_COMBO_BACK_COLOR            1008
#define IDC_COMBO_TEXT_COLOR            1009
#define IDC_COMBO_LINK_COLOR            1010
#define IDC_COMBO_FLINK_COLOR           1011
#define IDC_COMBO_PORT                  1012
#define IDC_COMBO_PLINK_COLOR           1012
#define ID_BACK_CLR_0                   1020
#define ID_BACK_CLR_1                   1021
#define ID_BACK_CLR_2                   1022
#define ID_BACK_CLR_3                   1023
#define ID_BACK_CLR_4                   1024
#define ID_BACK_CLR_5                   1025
#define ID_BACK_CLR_6                   1026
#define ID_BACK_CLR_7                   1027
#define ID_BACK_CLR_8                   1028
#define ID_BACK_CLR_9                   1029
#define ID_FORE_CLR_0                   1040
#define ID_FORE_CLR_1                   1041
#define ID_FORE_CLR_2                   1042
#define ID_FORE_CLR_3                   1043
#define ID_FORE_CLR_4                   1044
#define ID_FORE_CLR_5                   1045
#define ID_FORE_CLR_6                   1046
#define ID_FORE_CLR_7                   1047
#define ID_FORE_CLR_8                   1048
#define ID_FORE_CLR_9                   1049
#define IDC_USR_NAME                    1050
#define IDC_PASSWORD                    1051
#define IDC_LOGIN_PASSWORD              1051
#define IDC_SSN_NAME                    1052
#define IDC_LOGIN_USERNAME              1054
#define IDC_LOGIN_NEW_ACCOUNT           1055
#define IDC_CHACO_LOGO                  1060
#define IDC_LOGIN_SIGN_ON               1063
#define IDC_CONN_EDIT_PORT              1065
#define IDC_USE_LOCAL_MODULES           1067
#define IDC_HTML_VIEW                   1069
#define IDC_CHOOSE_PROPORTIONAL         1071
#define IDC_CHOOSE_FIXED                1072
#define IDC_STAT_PROPORTIONAL           1073
#define IDC_STAT_FIXED                  1074
#define IDC_NAME_1                      1075
#define IDC_NAME_2                      1076
#define IDC_NAME_3                      1077
#define IDC_NAME_4                      1078
#define IDC_NAME_5                      1079
#define IDC_EDIT_FIRST_NAME             1080
#define IDC_EDIT_LAST_NAME              1081
#define IDC_EDIT_MIDDLE_NAME            1082
#define IDC_EDIT_STREET                 1083
#define IDC_EDIT_CITY                   1085
#define IDC_EDIT_STATE                  1086
#define IDC_EDIT_ZIP                    1087
#define IDC_EDIT_EMAIL                  1088
#define IDC_EDIT_BIRTHDATE              1089
#define IDC_EDIT_APT                    1089
#define IDC_RADIO_MALE                  1090
#define IDC_RADIO_SEX_MALE              1090
#define IDC_EDIT_COUNTRY                1090
#define IDC_RADIO_FEMALE                1091
#define IDC_RADIO_SEX_FEMALE            1091
#define IDC_CACHE_SIZE                  1091
#define IDC_RADIO_SEX_OTHER             1092
#define IDC_CLR_CACHE                   1092
#define IDC_RADIO_SEX_OTHER2            1093
#define IDC_RADIO_SEX_NOYB              1093
#define IDC_CACHE_DIR                   1093
#define IDC_MAX_CONN                    1094
#define IDC_TEXT_PLACEHOLDER            1096
#define IDC_VERSION_STRING              1097
#define IDC_LOCBAR                      1099
#define IDC_VRFY_SESSION                1100
#define IDC_EDIT_LOC                    1100
#define IDC_VRFY_EVERYTIME              1101
#define IDC_CURR_URL                    1101
#define IDC_VRFY_NEVER                  1102
#define IDC_NET_ACTIVE                  1102
#define IDC_PROD_NAME                   1104
#define IDC_COPYRIGHT                   1105
#define IDC_CLAUSE                      1106
#define IDC_LEGEND                      1107
#define IDC_STATIC_VERSION              1115
#define IDC_SAMPLE_BACK                 1117
#define IDC_SAMPLE_TEXT                 1118
#define IDC_SAMPLE_LINK                 1119
#define IDC_SAMPLE_FLINK                1120
#define IDC_SAMPLE_PLINK                1121
#define ID_EDIT_PREFERENCES             32771
#define ID_FILE_LOGOUT                  32778
#define ID_FILE_LOGIN                   32779
#define ID_FILE_OPEN_LOC                32780
#define ID_VIEW_RELOAD                  32781
#define ID_VIEW_REFRESH                 32782
#define ID_GO_BACK                      32783
#define ID_GO_FORWARD                   32784
#define ID_GO_HOME                      32785
#define ID_GO_STOP_LOADING              32786
#define DI_BOOKMARK_ADD                 32787
#define ID_BOOKMARK_VIEW                32788
#define ID_BOOKMARK_ADD                 32789
#define IDS_TITLE_PREFS_DLG             61446
#define IDS_PWD_UN_EQUAL                61447
#define IDS_ABOUT_TITLE                 61448
#define IDS_CONNECT_FAILED              61449
#define IDS_GREETING_TIMEOUT            61450
#define IDS_OFFLINE                     61451
#define IDS_ONLINE                      61452
#define IDS_DISCLAIMER1                 61453
#define IDS_ACCOUNT_TITLE_FMT           61453
#define IDS_ACCOUNT_NAME_ERROR          61454
#define IDS_ACCOUNT_ADDRESS_ERROR       61455
#define IDS_ACCOUNT_INVALID             61456
#define IDS_ACCOUNT_IN_USE              61457
#define IDS_STATUS_CONNECTING           61458
#define IDS_STATUS_LOGGING_IN           61459
#define IDS_STATUS_INVALID_CLIENT       61460
#define IDS_ACCOUNT_NOT_COMPLETE        61460
#define IDS_PREV_PANE                   61461
#define IDS_NEXT_PANE                   61462
#define IDS_DONE                        61463
#define IDS_TEAM_GLENN                  61464
#define IDS_TEAM_JIM                    61465
#define IDS_TEAM_PRITHAM                61466
#define IDS_TEAM_RON                    61467
#define IDS_TEAM_DAN                    61468
#define IDS_LOGOUT_CONFIRM              61469
#define IDS_INVALID_CACHE_DIR           61470
#define IDS_STATUS_FETCHING_LICENSE     61471
#define IDS_NETDOWN                     61472
#define IDS_PROGRESS_BAR                61473
#define IDS_ERROR_404                   61474
#define IDS_ERROR_301                   61475
#define IDS_ERROR_302                   61476
#define IDS_ERROR_408                   61477
#define IDS_ERROR_501                   61478
#define IDS_ERROR_502                   61479
#define IDS_ERROR_504                   61480
#define IDS_ERROR_400                   61481
#define IDS_ERROR_503                   61482
#define IDS_ERROR_602                   61483
#define IDS_ERROR_603                   61484
#define IDS_ERROR_604                   61485
#define IDS_ERROR_608                   61486
#define IDS_ERROR_5XX                   61487
#define IDS_ERROR_4XX                   61488
#define IDS_TEXT_COLOR                  61489
#define IDS_OPEN_WEB_TRACKER_FILTER     61497

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
