# Makefile for Chaco Communications server

# If TOP is defined, we're being included by someone, so don't define these
ifeq ($(TOP),)
TOP = ..
SUBDIRS = client server
SOURCES = /dev/null
endif

include $(TOP)/Make.inc

# DO NOT DELETE
